# Reusable action for building and deploying to Cloudflare Pages
# Handles both Flutter chart component and main application builds
name: "Build and Deploy to Cloudflare Pages"
description: "Reusable action to build and deploy the application to Cloudflare Pages"

inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  cloudflare_account_id:
    description: "Cloudflare Account ID"
    required: true
  project_name:
    description: "Cloudflare Pages project name"
    required: true
  branch_name:
    description: "Branch name for deployment"
    required: true
  node_version:
    description: "Node.js version"
    required: false
    default: "20.x"
  flutter_version:
    description: "Flutter version"
    required: false
    default: "3.24.1"
  flutter_web_renderer:
    description: "Flutter web renderer"
    required: false
    default: "html"
  environment:
    description: "Deployment environment (production/preview)"
    required: false
    default: "preview"
  commit_hash:
    description: "Commit hash for deployment"
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: "npm"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: stable

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build Flutter chart component
      shell: bash
      env:
        FLUTTER_WEB_RENDERER: ${{ inputs.flutter_web_renderer }}
      run: |
        cd chart_app
        flutter pub get
        flutter build web --web-renderer "$FLUTTER_WEB_RENDERER" --release --no-tree-shake-icons
        cd ..

    - name: Build application
      shell: bash
      run: npm run build:app

    - name: Validate build output
      shell: bash
      run: |
        if [ ! -d "dist" ]; then
          echo "Error: dist directory not found. Build may have failed."
          exit 1
        fi
        if [ ! -f "index.html" ]; then
          echo "Error: index.html not found."
          exit 1
        fi
        echo "Build validation passed"

    - name: Prepare deployment files
      shell: bash
      run: |
        mkdir -p deploy
        cp index.html manifest.json sw.js nojs-smartcharts.css deploy/
        cp -r dist deploy/ # This is intentional, because of the way the paths are structured
        cp -r dist/* deploy/
        if [ -d "sass/favicons" ]; then
          mkdir -p deploy/sass
          cp -r sass/favicons deploy/sass/
        fi
        echo "Deployment files prepared successfully"

    - name: Install Wrangler
      shell: bash
      run: npm install -g wrangler@latest

    - name: Deploy to Cloudflare Pages
      id: deploy
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
        PROJECT_NAME: ${{ inputs.project_name }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
      run: |
        set -e
        echo "Starting deployment to Cloudflare Pages..."

        # Run the deployment
        wrangler pages deploy deploy \
          --project-name="$PROJECT_NAME" \
          --branch "$BRANCH_NAME" \
          --commit-hash="$COMMIT_HASH"

        echo "Deployment completed successfully"
