# Reusable action for building and deploying to Cloudflare Pages
# Handles both Flutter chart component and main application builds
name: "Build and Deploy to Cloudflare Pages"
description: "Reusable action to build and deploy the application to Cloudflare Pages"

inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  cloudflare_account_id:
    description: "Cloudflare Account ID"
    required: true
  project_name:
    description: "Cloudflare Pages project name"
    required: true
  branch_name:
    description: "Branch name for deployment"
    required: true
  node_version:
    description: "Node.js version"
    required: false
    default: "20.x"
  flutter_version:
    description: "Flutter version"
    required: false
    default: "3.24.1"
  flutter_web_renderer:
    description: "Flutter web renderer"
    required: false
    default: "html"
  environment:
    description: "Deployment environment (production/preview)"
    required: false
    default: "preview"
  commit_hash:
    description: "Commit hash for deployment"
    required: true

outputs:
  deployment_url:
    description: "Primary deployment URL"
    value: ${{ steps.deploy.outputs.deployment_url }}
  all_urls:
    description: "All URLs found in Cloudflare output"
    value: ${{ steps.deploy.outputs.all_urls }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full history needed for proper commit tracking

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: "npm"

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        channel: stable

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build Flutter chart component
      shell: bash
      run: |
        cd chart_app
        flutter pub get
        flutter build web --web-renderer ${{ inputs.flutter_web_renderer }} --release
        cd ..

    - name: Build application
      shell: bash
      run: npm run build:app

    - name: Validate build output
      shell: bash
      run: |
        if [ ! -d "dist" ]; then
          echo "Error: dist directory not found. Build may have failed."
          exit 1
        fi
        if [ ! -f "index.html" ]; then
          echo "Error: index.html not found."
          exit 1
        fi
        echo "Build validation passed"

    - name: Prepare deployment files
      shell: bash
      run: |
        mkdir -p deploy
        cp index.html manifest.json sw.js nojs-smartcharts.css deploy/
        cp -r dist deploy/ # This is intentional, because of the way the paths are structured
        cp -r dist/* deploy/
        if [ -d "sass/favicons" ]; then
          mkdir -p deploy/sass
          cp -r sass/favicons deploy/sass/
        fi
        echo "Deployment files prepared successfully"

    - name: Install Wrangler
      shell: bash
      run: npm install -g wrangler@latest

    - name: Deploy to Cloudflare Pages
      id: deploy
      shell: bash
      run: |
        set -e
        echo "Starting deployment to Cloudflare Pages..."

        # Run the deployment and capture output
        DEPLOY_OUTPUT=$(wrangler pages deploy deploy \
          --project-name=${{ inputs.project_name }} \
          --branch ${{ inputs.branch_name }} \
          --commit-hash=${{ inputs.commit_hash }} 2>&1)

        # Output the result of the deployment
        echo "$DEPLOY_OUTPUT"

        # Extract URLs from Cloudflare output
        DERIV_CLOUD_URL=""
        PAGES_DEV_URL=""

        # Look for URLs in the Cloudflare output
        while IFS= read -r line; do
          if [[ $line == *"https://"*".deriv.cloud"* ]]; then
            DERIV_CLOUD_URL=$(echo "$line" | grep -oE 'https://[^[:space:]]+\.deriv\.cloud[^[:space:]]*' | head -1)
          elif [[ $line == *"https://"*".pages.dev"* ]]; then
            PAGES_DEV_URL=$(echo "$line" | grep -oE 'https://[^[:space:]]+\.pages\.dev[^[:space:]]*' | head -1)
          fi
        done <<< "$DEPLOY_OUTPUT"

        echo "=== Extracted URLs from Cloudflare ==="
        echo "Deriv Cloud URL: $DERIV_CLOUD_URL"
        echo "Pages Dev URL: $PAGES_DEV_URL"

        # Prioritize .deriv.cloud over .pages.dev
        PRIMARY_URL=""
        ALTERNATE_URL=""

        if [[ -n "$DERIV_CLOUD_URL" ]]; then
          PRIMARY_URL="$DERIV_CLOUD_URL"
          ALTERNATE_URL="$PAGES_DEV_URL"
          echo "Primary URL: $DERIV_CLOUD_URL (deriv.cloud found)"
        elif [[ -n "$PAGES_DEV_URL" ]]; then
          PRIMARY_URL="$PAGES_DEV_URL"
          ALTERNATE_URL=""
          echo "Primary URL: $PAGES_DEV_URL (pages.dev fallback)"
        else
          echo "Warning: No URLs found in Cloudflare output"
          PRIMARY_URL=""
          ALTERNATE_URL=""
        fi

        # Create comma-separated list of all URLs (filter out empty ones)
        ALL_URLS=""
        if [[ -n "$DERIV_CLOUD_URL" ]]; then
          ALL_URLS="$DERIV_CLOUD_URL"
        fi
        if [[ -n "$PAGES_DEV_URL" ]]; then
          if [[ -n "$ALL_URLS" ]]; then
            ALL_URLS="$ALL_URLS,$PAGES_DEV_URL"
          else
            ALL_URLS="$PAGES_DEV_URL"
          fi
        fi

        echo "deployment_url=$PRIMARY_URL" >> $GITHUB_OUTPUT
        echo "all_urls=$ALL_URLS" >> $GITHUB_OUTPUT
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
