name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Remove PR Preview
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ -d "pr-preview/$PR_NUMBER" ]; then
            git rm -rf "pr-preview/$PR_NUMBER"
            git commit -m "Remove PR preview for #$PR_NUMBER"
            git push origin gh-pages
          else
            echo "No preview directory found for PR #$PR_NUMBER"
          fi
          
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## 🧹 Preview deployment cleaned up\n\nThe preview deployment for this PR has been removed.`
            });
