name: Deploy Preview

on:
  pull_request:
    branches:
      - master

env:
  FLUTTER_VERSION: '3.24.1'
  FLUTTER_WEB_RENDERER: 'html'
  NODE_VERSION: '20.x'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
      statuses: write

    steps:
      - name: Generate branch slug
        id: branch-slug
        run: |
          BRANCH_SLUG=$(echo "${{ github.head_ref }}" | sed 's|/|-|g' | sed 's|[^a-zA-Z0-9_-]||g')
          echo "branch_slug=$BRANCH_SLUG" >> $GITHUB_OUTPUT

      - name: Deploy to Cloudflare Pages
        uses: ./.github/actions/build-and-deploy
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          project_name: 'smartcharts-champion'
          branch_name: ${{ steps.branch-slug.outputs.branch_slug }}
          node_version: ${{ env.NODE_VERSION }}
          flutter_version: ${{ env.FLUTTER_VERSION }}
          flutter_web_renderer: ${{ env.FLUTTER_WEB_RENDERER }}
